var tableauQuestion = [
    {   question : "If you are driving at 80 kmh, and you approach a residential area, it means that",
        propositionA : "You will need to speed up ahead",
        propositionB : "You can speed through as long as there are no other cars",
        propositionC : "You will have to slow down up ahead",
        propositionD : "You can maintain your speed",
        reponse : "C"},
		
    {   question : "While turning left on a green light, you see that a pedestrian is in the crosswalk. Who has the right of way?",
        propositionA : "The pedastrian, because they can cross the road with any light",
        propositionB : "Your vehicle because the light is green",
        propositionC : "The pedastrian, because s/he is crossing with the green light",
        propositionD : "Your vehicle, because vehicles are always given right-of-way",
        reponse : "C"},
		
    {   question : "Unless posted, the maximum speed in a residential area is ____ kmh.",
        propositionA : "50",
        propositionB : "55",
        propositionC : "65",
        propositionD : "70",
        reponse : "A"},
	
	{   question : "Before every lane change, you should.",
        propositionA : "Check your mirrors",
        propositionB : "Check your blind spots",
        propositionC : "Signal your intentions",
        propositionD : "All of the above",
        reponse : "D"},
		
	{   question : "What blood alcohol level is classified as driving while intoxicated?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},
		
	{   question : "You must pull over and stop until any emergency vehicle with a siren has passed, unless:",
        propositionA : "You are in a hurry",
        propositionB : "There is enough room for them in a nother lane",
        propositionC : "You are in a school zone",
        propositionD : "You are in an intersection",
        reponse : "D"},
	
	{   question : "Right-of-way must be yielded to emergency vehicles",
        propositionA : "At all times",
        propositionB : "Flashing red, blue, or white lights",
        propositionC : "Using a siren or flashing red, blue, or white lights",
        propositionD : "Using a siren",
        reponse : "C"},
		
	{   question : "Which of the following IS permitted when passing another vehicle?",
        propositionA : "Following closely",
        propositionB : "Leaving the main traveled roadway",
        propositionC : "Driving on the opposite side of the road",
        propositionD : "Exceeding the speed limit",
        reponse : "C"},
		
	{   question : "You are driving on a freeway with a posted speed limit of 110 kmh. Most of the traffic is traveling at 120 mph, so you should be driving no faster than",
        propositionA : "80 kmh",
        propositionB : "40 kmh",
        propositionC : "50 kmh",
        propositionD : "110 kmh",
        reponse : "D"},
		
	{   question : "When being passed by another vehicle, it is important NOT to",
        propositionA : "Slow down",
        propositionB : "Check your mirrors",
        propositionC : "Look at the other driver",
        propositionD : "Speed up",
        reponse : "D"},
]
